---
- name: Cleanup
  hosts: all
  tasks:

    - name: Ansible check file exists example.
      stat:
        path: "{{ infrared_venv }}/bin/activate"
      register: former_venv

    - name: "Uninstall ansible-role-collect-logs plugin"
      shell: |
        export PATH=$PATH:/usr/local/sbin:/usr/sbin
        source {{ infrared_venv }}/bin/activate
        ir plugin remove ansible-role-collect-logs
        ir plugin list
      args:
        executable: /bin/bash
      register: plugin_uninstall_output
      when: former_venv.stat.exists

    - name: "Debug, plugin uninstallation"
      debug:
        msg: "{{ plugin_uninstall_output }}"

    - name: "Clean Infrared venv"
      file:
        path: "{{ infrared_location }}"
        state: absent
