---
# vars are defined molecule.yml to avoid repeading them for each play
- name: Create collection dir play
  hosts: localhost
  tasks:

    - name: Create temp collection folder
      file:
        path: "{{ local_working_dir }}"
        state: directory

- name: Converge
  hosts: all
  strategy: free
  tasks:

    - name: "Include ansible-role-collect-logs :: collect"
      include_role:
        name: "ansible-role-collect-logs"
        tasks_from: collect.yml
